{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719749622669\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x000002799F538380>\nuser_page = <pages.user_page.UserPage object at 0x000002799F5391F0>\ncreated_user = <config.data.user_data object at 0x000002799F539460>\nlogger = <utils.logger.Logger object at 0x000002799F5398B0>\n\n    def test_login_with_wrong_data(self, user_page, created_user, logger):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            logger.info(\"Вход в систему с недействительными учетными данными...\")\n            logger.info(f\"Username: {created_user.username}\")\n            logger.info(\"Пароль: wrongpassword123\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword123\")\n    \n            logger.info(f\"HTTP статус код ответа: {response.status_code}\")\n            logger.info(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n                logger.info(f\"Заголовки ответа: {response.headers}\")\n    \n>           assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\nE           AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719749622669\"}\nE           assert 200 == 400\nE            +  where 200 = <Response [200]>.status_code\n\ntest_user_operations.py:233: AssertionError"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719749622669\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 233, in test_login_with_wrong_data\n    assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "60284fea-f186-406d-9801-4e6ff040a829-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "49c6e46a-4e92-49b8-8a40-19f6f58aa819-attachment.json", "type": "application/json"}], "start": 1719749623744, "stop": 1719749623745}], "start": 1719749622482, "stop": 1719749623746}], "attachments": [{"name": "log", "source": "75881147-3a9c-4c7b-9b2a-d2ed2b8a3334-attachment.txt", "type": "text/plain"}], "start": 1719749622482, "stop": 1719749623746, "uuid": "26e0f7fe-984d-4f19-b022-fda112396983", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "6832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}