{"name": "test_login_with_invalid_credentials", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('created_user', <FixtureRequest for <Function test_login_with_invalid_credentials>>)", "trace": "file C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py, line 104\n      def test_login_with_invalid_credentials(self, user_page, created_user):\nE       fixture 'created_user' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, faker, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_data, user_page\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py:104"}, "start": 1719737297703, "stop": 1719737297703, "uuid": "1f27a95a-c3b7-4b22-bd72-86c89b0adbab", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "11512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}