{"name": "test_login_with_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: User creation response does not contain user id\nassert 'id' in {'code': 200, 'message': '5', 'type': 'unknown'}", "trace": "user_page = <pages.user_page.UserPage object at 0x00000203D63C4E00>\nuser_data = <config.data.user_data object at 0x00000203D63C4F50>\n\n    @pytest.fixture(scope=\"module\")\n    def created_user(user_page, user_data):\n        response = user_page.create_user(user_data.__dict__)\n        assert response.status_code == 200, response.text\n        # Проверяем, что ответ содержит данные пользователя и возвращаем их, если это так\n        user_response_data = json.loads(response.text)\n        # Проверяем, что response содержит id пользователя\n>       assert 'id' in user_response_data, \"User creation response does not contain user id\"\nE       AssertionError: User creation response does not contain user id\nE       assert 'id' in {'code': 200, 'message': '5', 'type': 'unknown'}\n\n..\\conftest.py:21: AssertionError"}, "start": 1719738655626, "stop": 1719738655626, "uuid": "ccc76a65-2703-4eea-b0bf-1f9d96b04696", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "14288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}