{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719748802502\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x0000013D7A3346B0>\nuser_page = <pages.user_page.UserPage object at 0x0000013D7A2088C0>\ncreated_user = <config.data.user_data object at 0x0000013D7A209760>\nlogger = <utils.logger.Logger object at 0x0000013D7A208800>\n\n    def test_login_with_wrong_data(self, user_page, created_user, logger):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            print(\"Вход в систему с недействительными учетными данными...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Пароль: wrongpassword123\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword123\")\n    \n            print(f\"HTTP статус код ответа: {response.status_code}\")\n            print(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n>           assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\nE           AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719748802502\"}\nE           assert 200 == 400\nE            +  where 200 = <Response [200]>.status_code\n\ntest_user_operations.py:222: AssertionError"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719748802502\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 222, in test_login_with_wrong_data\n    assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "4fe2b989-ae3c-4961-9562-6bff008fd3c3-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "6fdcf0e8-97c8-4d8a-8a51-56cc71206bed-attachment.json", "type": "application/json"}], "start": 1719748803577, "stop": 1719748803578}], "start": 1719748802461, "stop": 1719748803578}], "attachments": [{"name": "stdout", "source": "153db4c9-9613-491f-8da8-92e09379fe96-attachment.txt", "type": "text/plain"}], "start": 1719748802461, "stop": 1719748803579, "uuid": "2bd3b8a1-cebe-46d1-897b-e9f6f596df2f", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "9544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}