{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "Failed: Unexpected successful login with wrong data. Response: {'code': 200, 'type': 'unknown', 'message': 'logged in user session:1719743980381'}", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x0000021D0B1F3770>\nuser_page = <pages.user_page.UserPage object at 0x0000021D0B168770>\ncreated_user = <config.data.user_data object at 0x0000021D0B14C860>\n\n    def test_login_with_wrong_data(self, user_page, created_user):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            print(\"Вход в систему с недействительными учетными данными...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Пароль: wrongpassword\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword\")\n    \n            print(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n            if response.headers.get('Content-Type') == 'application/json':\n                response_json = response.json()\n    \n                print(f\"Фактическое тело ответа: {response_json}\")  # Print actual response\n    \n    \n                if response_json.get(\"code\") == 200 and \"logged in user session:\" in response_json.get(\"message\", \"\"):\n>                   pytest.fail(f\"Unexpected successful login with wrong data. Response: {response_json}\")\nE                   Failed: Unexpected successful login with wrong data. Response: {'code': 200, 'type': 'unknown', 'message': 'logged in user session:1719743980381'}\n\ntest_user_operations.py:192: Failed"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "Failed: Unexpected successful login with wrong data. Response: {'code': 200, 'type': 'unknown', 'message': 'logged in user session:1719743980381'}\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 192, in test_login_with_wrong_data\n    pytest.fail(f\"Unexpected successful login with wrong data. Response: {response_json}\")\n  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "28073794-2912-4d7c-96fd-24c438f19cc6-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "588ddd27-a3cc-4cd4-8def-2bce6faf1698-attachment.json", "type": "application/json"}], "start": 1719743981416, "stop": 1719743981417}], "start": 1719743980299, "stop": 1719743981417}], "attachments": [{"name": "stdout", "source": "1426aab6-f435-496c-a4a2-14f844009b21-attachment.txt", "type": "text/plain"}], "start": 1719743980299, "stop": 1719743981418, "uuid": "e90c29bb-84cf-4f32-be12-e5d6e2079c4b", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "15428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}